== Apache ActiveMQ Artemis

This example shows how to setup connection factory to a remote Apache ActiveMQ Artemis
messaging broker.

=== Apache ActiveMQ Artemis

You first need to have an ActiveMQ Artimis broker up and running.
See more at: https://activemq.apache.org/components/artemis/


=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

Or run with JBang using the longer command line (without installing camel as app in JBang):

[source,sh]
----
$ jbang camel@apache/camel run *
----

=== Artemis configuration

See the `application.properties` for how to configure to the ActiveMQ Artemis broker.


=== Developer Web Console

You can enable the developer console via `--console` flag as show:

[source,sh]
----
$ camel run * --console
----

Then you can browse: http://localhost:8080/q/dev to introspect the running Camel applicaton.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
