== JBang Edit

This example shows how to use JBang to edit the source code by using the jbang CLI
to download dependencies and setup project for being ready to load into an IDE of choice,
such as IDEA, VSCode, or Eclipse.

 === Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run foo.java
----

Or run with JBang using the longer command line (without installing camel as app in JBang):

[source,sh]
----
$ jbang camel@apache/camel run foo.java
----

=== Editing source via jbang

To make it easy to load the project into a Java editor such as IDEA or VSCode, then we can use jbang CLI for this.

[source,sh]
----
$ jbang edit -b foo.java
----

JBang will then prepare for the project and ask you which IDE to use.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
