== XML to YAML

This example shows XML DSL with both bean and routes using the new <camel> root tag.

The XML can be migrated to YAML DSL using Camel JBang.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

=== Transforming to YAML

The example will on startup transform the source from XML to YAML and save
this into dump sub directory.

This can also be done explicit from CLI, by executing:

[source,sh]
----
$ camel transform * --format=yaml --directory=my-dump
----

This will transform the Camel XML DSL into YAML and store the output in the my-dump directory.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
