== XML to YAML

This example shows classic Spring XML file with <bean> and <camelContext> with embedded <route>.

The XML can be migrated to YAML DSL using Camel JBang.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

=== Transforming to YAML

The example will on startup transform the source from XML to YAML and save
this into dump sub directory (or print to console).

This can also be done explicit from CLI, by executing:

[source,sh]
----
$ camel transform * --format=yaml --output=my-dump
----

This will transform the XML DSL into YAML DSL and store the output in the my-dump directory.

If you want to print the dump to console, you can do:

[source,sh]
----
$ camel transform * --format=yaml
----

And since yaml is default format, it can be shorter:

[source,sh]
----
$ camel transform *
----


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
