== Main Profile

This example shows how you can use Camel JBang with profiles
to run for development, testing or production.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run hello.camel.yaml
----

This will run in developer mode by deafult (default in Camel JBang)

You can run in another profile with:

[source,sh]
----
$ camel run hello.camel.yaml --profile=production
----

And if you want to turn off profile, you can use an empty value (or none)

[source,sh]
----
$ camel run hello.camel.yaml --profile=
----

Notice how the application prints different message depending on the selected profile.
This is due to the loaded properties file that is profile specific.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
