# use http server
camel.server.enabled=true
camel.server.staticEnabled=true

# use https instead of http with self-signed certificate
# making it easy for development purpose
#camel.ssl.enabled=true
#camel.ssl.selfSigned=true