== HTML Chat

This example is a small chat web application.

The web app is the index.html and style.css file that will show the chat window.
The Camel route is in the server.xml file, and will return a response to the chat.

The application.properties file is used to turn on serving the web application
with the embedded HTTP server in Camel.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

Then you can browse: http://localhost:8080/ to chat with Camel.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
