- route:
    nodePrefixId: route-e2a
    id: route-8847
    from:
      uri: timer
      id: from-0922
      parameters:
        timerName: timer1
        delay: '1000'
        period: '5000'
      steps:
        - setBody:
            expression:
              simple:
                expression: Hello World
                id: simple-3fc3
            id: setBody-b8e4
        - to:
            uri: direct
            id: to-280f
            parameters:
              name: direct1
- route:
    nodePrefixId: route-6ce
    id: route-a9b6
    from:
      uri: direct
      id: from-a1fa
      parameters:
        name: direct1
      steps:
        - setBody:
            constant: 'HELLO'
            id: log-dcfc
- rest:
    id: rest-8cd4
    post:
      - path: /rest-api
        to: direct:direct1
        id: post-032f
