apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer-kafka-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: "Camel-test"
      period: 30000
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-not-secured-sink
    properties:
      bootstrapServers: "<cluster>:9092"
      topic: "my-topic"
