== Sending message to Servicebus and consume them

In this sample you'll use the Azure Servicebus source and sink Kamelet based on camel-azure-servicebus component.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== Terraform steps

[source,sh]
----
$ cd terraform/
----

First of all init terraform

[source,sh]
----
$ terraform init
----

Then run the command to apply your configuration to your Azure account

[source,sh]
----
$ terraform apply -var="services_bus_namespace_name=<namespace_name>" -var="resource_group_name=<resource_name>" -var="location=<location>" -var="messages_queue_name=<queue_name>" -out tfout.log
----

Correctly populating the various field for your needs

Once the process will complete you'll get a sensitive output for the primary connection String

You're now able to read the sensitive data with

[source,sh]
----
terraform output --raw messages_queue_name
----

This string should be used in the application.properties file.

=== How to run the producer

Then you can run this producer example using:

[source,sh]
----
$ jbang -Dcamel.jbang.version=4.5.0-SNAPSHOT camel run timer-to-azure-servicebus.yaml
----

=== How to run the consumer

Then you can run this consumer example using:

[source,sh]
----
$ jbang -Dcamel.jbang.version=4.5.0-SNAPSHOT camel run azure-servicebus-to-log.yaml
----


