== Pipe

This example shows how to use Camel with terminal scripting.

There are 2 scripts:

- `upper.yaml` - Upper cases the input
- `to_csv.java` - Aggregates the input into a single comma separated output

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To make the example runnable as a script, you must ensure the files
has execution permission:

[source,sh]
----
chmod +x upper.yaml
chmod +x to_csv.java
----

To run this example you can then run the script:

[source,sh]
----
echo "Hello\nWorld" | ./upper.yaml
----

You can combine this with more pipes and filters scripting.

In the example below the file words.txt contains a set of names, which is then piped
into the Camel script to be upper cased, then piped to the sort command from the terminal,
and then back into Camel to be converted into CSV.

[source,sh]
----
cat words.txt | ./upper.yaml | sort | ./to_csv.java
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
