== Pipe

This example shows how to use Camel with terminal scripting.
The script is coded in Java in the `to_csv.java` file.

The script reads from system:in (using the camel stream component)
which automatic will split the input line by line. Each line
is aggregated and assembled into a single comma separated output,
that is routed to system:out.

Yes this is overkill to use Camel to transform such kind of task,
but we wanted to keep this example simple, but use EIPs instead
of a basic from -> to route.


=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To make the example runnable as a script, you must ensure the file
has execution permission:

[source,sh]
----
chmod +x to_csv.java
----

To run this example you can then run the script:

[source,sh]
----
echo "Hello\nWorld" | ./to_csv.java
----

You can combine this with more pipes and filters scripting such as.
For example from a file that has a set of words:

[source,sh]
----
cat words.txt | sort | ./to_csv.java
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
