== Chaos Monkey

This example shows a chaos moneky with Camel JBang.

When everything is okay then Camel reports UP in the helath check.
But the chaos monkey can from time to time cause problems and the health check is then DOWN.


=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

Or run with JBang using the longer command line (without installing camel as app in JBang):

[source,sh]
----
$ jbang camel@apache/camel run *
----

=== Run directly from github

The example can also be run directly by referring to the github URL as shown:

[source,sh]
----
$ jbang camel@apache/camel run https://github.com/apache/camel-kamelets-examples/tree/main/jbang/chaos-monkey --health
----

=== Helath Check Console

You can enable the health check console via `--health` flag as show:

[source,sh]
----
$ camel run * --health
----

Then you can browse: http://localhost:8080/q/health to introspect the health check
of the running application. When the chaos moneky is causing problems then the check is DOWN otherwise its UP.

You can also inspect the health-check from CLI via:

[source,sh]
----
$ camel get health
----

The metrics can also be displayed from the shell via:

[source,sh]
----
$ camel get metric
----


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
