== HTTP Streaming

This example shows how Camel can continuously read HTTP streaming data, from a remote HTTP server.
The HTTP server is expected to send data back in chunks separated by new-line (HTTP streaming).

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

You need to run the HTTP server first which can be done using Java:

[source,sh]
----
$ java MyHttpServer.java
----

This starts a local HTTP server on port 8500

Then you can run this example using:

[source,sh]
----
$ camel run my-stream.yaml
----

Or run with JBang using the longer command line (without installing camel as app in JBang):

[source,sh]
----
$ jbang camel@apache/camel run mystream.yaml
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
