== Route Template

This example is using a route template as a skeleton route with configurable parameters.

Then 2 routes are created that uses the template with actual parameters,
which are configured in `application.properties`. 

This is to demonstrate how to build small _parameterized routes_ and also
use them easily, without any Java coding.


=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

==== Run in dev mode for hot-reload

You can run in dev mode, which allows you to edit the source files and hot-reload changes.

[source,sh]
----
$ camel run * --dev
----

=== Run directly from GitHub

The example can also be run directly by referring to the GitHub URL as shown:

[source,sh]
----
$ camel run https://github.com/apache/camel-kamelets-examples/tree/main/jbang/route-template
----


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
