== YAML with configuring Java bean via Builder class

An example, of using YAML DSL with configuring a Java bean using fluent builder class,
to be used in the Camel route.

This shows the flexibility of bean configuration in YAML DSL to make it possible
for non Java developers to configure beans that requires using fluent builder class,
with the power of low-code prgramming.


=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

=== Live reload

You can run the example in dev mode which allows you to edit the example,
and hot-reload when the file is saved.

[source,sh]
----
$ camel run * --dev
----


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
