== Variables with EIPs

This example shows how you can use variables with EIPs with Camel routes.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run myapp.yaml
----

Or run with wildcard:

[source,sh]
----
$ camel run *
----

You can also debug this application from camel-jbang with:

[source,sh]
----
$ camel debug * --show-exchange-variables
----

This runs the application in debug mode with a basic CLI debugger directly from the terminal.
To see the variables on the exchanges, then you can turn this on via `--show-exchange-variables`.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
