== ActiveMQ to FTP

This example shows how to integrate ActiveMQ with FTP server.

=== Running ActiveMQ and FTP server

You need both an ActiveMQ Artemis broker, and FTP server up and running.

You can run both via Docker Compose

[source,sh]
----
$ docker compose up --detach
----

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

=== Sending Messages to ActiveMQ

When the example is running, you need to trigger Camel, by sending messages to the ActiveMQ broker.
You can either do this via the broker web console http://localhost:8161 (login with `artemis/artemis`
or by using Camel JBang:

[source,sh]
----
$ camel cmd send --body=file:payload.xml
----

=== Browsing FTP server

When you have send some messages to ActiveMQ then Camel will route these to the FTP server.
To see which files has been uploaded, you can remote shell into Docker or use Camel JBang:

[source,sh]
----
$ camel cmd browse
----

Which shows a status page of pending messages in the systems.

To see the content of these messages, you can tell Camel to dump via

[source,sh]
----
$ camel cmd browse --dump
----

TIP: To see more options use `camel cmd browse --help`.


=== Developer Web Console

You can enable the developer console via `--console` flag as show:

[source,sh]
----
$ camel run * --console
----

Then you can browse: http://localhost:8080/q/dev to introspect the running Camel Application.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
