== Dependency Injection

This example shows how Camel JBang can use dependency injection annotations
from Spring Boot or Quarkus, to wire up Java beans.

The runtime is still plain Camel Main with JBang, and not Spring Boot or Quarkus.
However the benefit of allowing to use their annotations is that the transition
from Camel JBang to Spring Boot or Quarkus is easier.


=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run *
----

Or run with JBang using the longer command line (without installing camel as app in JBang):

[source,sh]
----
$ jbang camel@apache/camel run *
----


=== Live reload

You can run the example in dev mode which allows you to edit the example,
and hot-reload when the file is saved.

[source,sh]
----
$ camel run * --dev
----


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
