== Timer to Azure Storage Blob Sink

In this sample you'll use the Azure Storage Blob Append Sink Kamelet based on camel-azure-storage-blob component.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== Setup credentials

In the `application.properties` add the correct accessKey, accountName and containerName for the Azure Storage Blob account.

=== How to run

Then you can run this example using:

[source,sh]
----
$ camel run --local-kamelet-dir=<local-kamelets-dir> timer-append-blob.camel.yaml
----

Replace the local kamelet dir with your local directory.

=== Developer Web Console

You can enable the developer console via `--console` flag as show:

[source,sh]
----
$ jbang run --fresh camel@apache/camel run --local-kamelet-dir=<path_to_local_kamelet_dir> timer-append-blob.camel.yaml --console
----

Then you can browse: http://localhost:8080/q/dev to introspect the running Camel Application.


=== Verify the sink worked

After a while you should find different files with different name and date. Each of these file will contain two entries (one every 30 seconds).

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
